import { Adventure } from "@/interfaces/Adventure";

export const internationalRoutes: Adventure[] = [
  {
    id: "some-id",
    title: "Circuito Canal de Panamá",
    firstDate: "18.05.2025",
    location: "Panamá",
    shortDescription: "Explora el Canal de Panamá en bici y descubre su historia en cada pedaleada.",
    longDescription: "En este recorrido urbano guiado de 3–4 horas recorrerás Casco Viejo, la Cinta Costera y los alrededores del Canal. Guiado por expertos Locales, incluirás paradas clave con historia y un merecido descanso con refrigerio Local.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "USD",
    price: 450000,
    duration: 2,
    category: "Internacional",
    capacity: 20,
    riders: 10
  },
  {
    id: "some-id",
    title: "Machu Picchu",
    firstDate: "22.06.2025",
    location: "Perú",
    shortDescription: "Ruta en bicicleta por cenotes, selva y ruinas mayas alrededor de Tulum.",
    longDescription: "Durante este tour de medio día visitarás cenotes escondidos, senderos selváticos y pasadizos arqueológicos ocultos. Incluye transporte, guía bilingüe, lunch y entrada a sitio maya.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "USD",
    price: 450000,
    duration: 1,
    category: "Internacional",
    capacity: 15,
    riders: 15
  },
  {
    id: "some-id",
    title: "Cruce de los Andes",
    firstDate: "05.07.2025",
    location: "Bolivia",
    shortDescription: "Aventura épica por el altiplano andino, desde Bolivia hasta Cusco.",
    longDescription: "Esta travesía de 10 días conecta poblaciones remotas, campos elevados y paisajes surrealistas como el Salar de Uyuni. Incluye hospedaje básico, soporte técnico y guías Locales expertos en alta montaña.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "USD",
    price: 3500000,
    duration: 2,
    category: "Internacional",
    capacity: 25,
    riders: 8
  },
  {
    id: "some-id",
    title: "Ruta de Volcanes",
    firstDate: "15.09.2025",
    location: "Ecuador",
    shortDescription: "Ruta circular que rodea volcanes como Cotopaxi y Quilotoa.",
    longDescription: "Durante cuatro días pedalearás por caminos de páramo, aldeas indígenas y miradores naturales. Estancia en hostales Locales y guías bilingües incluidos.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "USD",
    price: 900000,
    duration: 2,
    category: "Internacional",
    capacity: 18,
    riders: 12
  },
  {
    id: "some-id",
    title: "Patagonia Austral",
    firstDate: "1001.2026",
    location: "Argentina",
    shortDescription: "Terrenos remotos, vientos helados y vistas de glaciares en bicicleta.",
    longDescription: "Ruta de cinco días entre el Lago Argentino y El Chaltén, con paisajes glaciares, bosques y estepa patagónica. Incluye campamento, transfer aéreo y guía bilingüe.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "USD",
    price: 800000,
    duration: 2,
    category: "Internacional",
    capacity: 16,
    riders: 6
  }
];

export const nationalRoutes: Adventure[] = [
  {
    id: "some-id",
    title: "Cocora y Nevados",
    firstDate: "27.05.2025",
    location: "Quindío",
    shortDescription: "Palmas de cera, senderos de altura y café en vuelo de montaña.",
    longDescription: "Recorrido de un día que combina la emblemática palma de cera de Cocora con senderos panorámicos hacia el Parque de los Nevados. Incluye guía, transporte Local y refrigerio con café regional.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 750000,
    duration: 2,
    category: "Nacional",
    capacity: 25,
    riders: 18
  },
  {
    id: "some-id",
    title: "Sierra Nevada",
    firstDate: "15.08.2025",
    location: "Magdalena",
    shortDescription: "Desde el mar hasta nieves eternas: una ruta que retadora y única.",
    longDescription: "Aventura épica de múltiples días desde la costa caribeña hasta los picos nevados de la Sierra Nevada de Santa Marta.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "COP",
    price: 875000,
    duration: 2,
    category: "Nacional",
    capacity: 15,
    riders: 12
  },
  {
    id: "some-id",
    title: "Desierto de la Tatacoa",
    firstDate: "10.10.2025",
    location: "Huila",
    shortDescription: "Pedaleada entre formaciones caprichosas y cielos estrellados.",
    longDescription: "Recorrido nocturno y diurno por el desierto más famoso de Colombia, con observación astronómica incluida.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Fácil",
    currency: "COP",
    price: 540000,
    duration: 2,
    category: "Nacional",
    capacity: 30,
    riders: 10
  },
  {
    id: "some-id",
    title: "Tatamá Bosque Nuboso",
    firstDate: "12.09.2025",
    location: "Chocó",
    shortDescription: "Ríos, biodiversidad y la majestuosidad del bosque húmedo andino.",
    longDescription: "Ruta de dos días entre senderos selváticos y miradores, pasando por el Bosque del Tatamá. Hospedaje comunitario y guía experto incluidos.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 200000,
    duration: 2,
    category: "Nacional",
    capacity: 20,
    riders: 14
  },
  {
    id: "some-id",
    title: "Cañón del Chicamocha",
    firstDate: "05.10.2025",
    location: "Santander",
    shortDescription: "Vistas épicas desde una de las gargantas más grandes de América.",
    longDescription: "Aventura de día completo en bici por bordes del Cañón del Chicamocha. Incluye guía, transporte desde Bucaramanga y parada en miradores naturales.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "COP",
    price: 980000,
    duration: 2,
    category: "Nacional",
    capacity: 16,
    riders: 5
  }
];

export const localRoutes: Adventure[] = [
  {
    id: "some-id",
    title: "Jericó",
    firstDate: "12.05.2025",
    location: "Antioquia",
    shortDescription: "Pueblo del alma: cultura, ciclomontañismo y aire puro.",
    longDescription: "Salida desde Medellín temprano en la mañana con recorrido por zonas cafeteras, vistas panorámicas y almuerzo tradicional. Regreso por senderos Locales en bicicleta.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Fácil",
    currency: "COP",
    price: 270000,
    duration: 2,
    category: "Local",
    capacity: 25,
    riders: 19
  },
  {
    id: "some-id",
    title: "Amalfi",
    firstDate: "21.06.2025",
    location: "Antioquia",
    shortDescription: "Dos días de ciclismo y senderismo en los montes del oriente antioqueño.",
    longDescription: "Aventura combinada: un día en bici por caminos montañosos seguido de caminata por senderos y cascadas. Hospedaje Local incluido.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Fácil",
    currency: "COP",
    price: 405.000,
    duration: 2,
    category: "Local",
    capacity: 20,
    riders: 9
  },
  {
    id: "some-id",
    title: "Norcasia",
    firstDate: "18.08.2025",
    location: "Antioquia",
    shortDescription: "Senderos rurales entre colinas y comunidades agrícolas Locales.",
    longDescription: "Ruta de un día con vistas panorámicas, interacción con comunidades campesinas y gastronomía Local. Transporte en van incluido.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 203.000,
    duration: 2,
    category: "Local",
    capacity: 18,
    riders: 7
  },
  {
    id: "some-id",
    title: "Sonsón",
    firstDate: "05.09.2025",
    location: "Antioquia",
    shortDescription: "Circuito de montaña con ascensos suaves y paisajes verdes.",
    longDescription: "Ruta de ciclomontañismo suave entre caminos boscosos con vista del embalse y naturaleza circundante. Comida típica y regreso al atardecer.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 248.000,
    duration: 2,
    category: "Local",
    capacity: 25,
    riders: 2
  },
  {
    id: "some-id",
    title: "Santa Fe de Antioquia",
    firstDate: "1007.2025",
    location: "Antioquia",
    shortDescription: "Descenso técnico desde Santa Fe por senderos All‑Mountain y gravel.",
    longDescription: "Descenso de gran adrenalina desde ~2.800 m hasta zonas más cálidas, combinando carreteras rurales, caminos de finca y singletrack técnico. Requiere guía por seguridad.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Difícil",
    currency: "COP",
    price: 100000,
    duration: 2,
    category: "Local",
    capacity: 30,
    riders: 8
  },
  {
    id: "some-id",
    title: "Arví – Guatapé",
    firstDate: "22.08.2025",
    location: "Antioquia",
    shortDescription: "Desde Medellín hasta el embalse de Guatapé a través del Parque Arví",
    longDescription: "Primero en bici hasta Parque Arví vía metrocable, luego pedaleo por carreteras rurales hasta Guatapé. Paisajes de bosque, represa e íconos paisas como la Piedra del Peñol. Ideal ruta intermedia.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 420000,
    duration: 2,
    category: "Local",
    capacity: 20,
    riders: 5
  },
  {
    id: "some-id",
    title: "Nariño",
    firstDate: "10.12.2025",
    location: "Antioquia",
    shortDescription: "Pueblo pintoresco rodeado de montañas, famoso por su tranquilidad, arquitectura colonial y gente amable.",
    longDescription: "Nariño, Antioquia, es un encantador municipio enclavado en las montañas del suroeste antioqueño. Sus calles empedradas, fachadas coloridas y ambiente apacible invitan a recorrerlo sin prisa, disfrutando de su arquitectura colonial y del calor humano de sus habitantes. Rodeado de verdes paisajes, es un lugar perfecto para desconectarse, explorar la cultura cafetera y vivir la esencia de los pueblos tradicionales de Colombia.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 420000,
    duration: 2,
    category: "Local",
    capacity: 30,
    riders: 2
  },
  {
    id: "some-id",
    title: "La Danta",
    firstDate: "24.11.2025",
    location: "Antioquia",
    shortDescription: "Rutas naturales, cascadas y bosques. Una aventura que conecta con la tierra",
    longDescription: "Primero en bici hasta Parque Arví vía metrocable, luego pedaleo por carreteras rurales hasta Guatapé. Paisajes de bosque, represa e íconos paisas como la Piedra del Peñol. Ideal ruta intermedia.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 420000,
    duration: 2,
    category: "Local",
    capacity: 24,
    riders: 10
  },
  {
    id: "some-id",
    title: "San Rafel",
    firstDate: "05.12.2025",
    location: "Antioquia",
    shortDescription: "Paraíso natural de aguas cristalinas, cascadas y clima cálido ideal para el ecoturismo.",
    longDescription: "San Rafael, Antioquia, es un destino turístico privilegiado por su abundancia de ríos, quebradas y cascadas que forman pozos de aguas cristalinas ideales para nadar y relajarse. Ubicado en el oriente antioqueño, este municipio combina naturaleza exuberante, clima cálido y la hospitalidad propia de la región. Es un punto perfecto para el ecoturismo, el avistamiento de aves y las caminatas por senderos que conectan con impresionantes paisajes naturales.",
    image: {
      large: "",
      thumbnail: "",
      full: "",
    },
    difficulty: "Intermedia",
    currency: "COP",
    price: 420000,
    duration: 2,
    category: "Local",
    capacity: 25,
    riders: 23
  }
];

export const allRoutes: Adventure[] = [...internationalRoutes, ...nationalRoutes, ...localRoutes];